<p align="center"><b>Activity</b></p>

<p align="center">
  <img src="./assets/metrics.svg" width="640" alt="GitHub Metrics" />
</p>

<p align="center">
  <img src="./assets/github-snake.svg" width="640" alt="Contribution Snake" />
</p>
